### ISSUE TITLE
[BUG] vibrant-cli command is not working at startup

### ISSUE THREAD

**Issue by isayakmondal** [libvibrant/libvibrant#12]
I've tried to add `vibrant-cli eDP-1 1.25` in my starup application command in my `Ubuntu 22.04` but it doesn't seem to work for some reason. 
This is where my binary is located
![image](https://github.com/libvibrant/libvibrant/assets/51121313/c23d4998-e080-4f33-be9f-bfc9d00cf6f9)
Although it does work as intended while directly calling from the terminal.
![image](https://github.com/libvibrant/libvibrant/assets/51121313/aac775b4-74b6-43e7-aa25-30a069bb0bd5)

**Comment by Scrumplex** [comment]
This could be a race condition of some sorts (i.e. vibrant-cli is being called too early)

You could add a sleep to your start script to see if that does anything.

**Comment by isayakmondal** [comment]
Okay so did some further digging and manually added `xrandr --output eDP-1 --set CTM '715827882,1,357913941,-2147483648,357913941,-2147483648,357913941,-2147483648,715827882,1,357913941,-2147483648,357913941,-2147483648,357913941,-2147483648,715827882,1'`
this as my startup program but this also didn't work(but indeed works manually). So looks like it's has to written to a conf file in order for it to be president (or called at startup), but I'm not sure how to do that properly. @Scrumplex

**Comment by isayakmondal** [comment]
Yes, adding this to the startup does solve the issue apparently. Thanks for the suggestion!
```
#!/bin/bash

sleep 5
vibrant-cli eDP-1 1.25
```
