### ISSUE TITLE
Works on Intel HD520 (i5 6200u laptop cpu), but not on every distro.

### ISSUE THREAD

**Issue by golimonkey** [libvibrant/libvibrant#7]
Just wanna say that I tried libvibrant on few distributions and got different results for some reason. If i remember correctly mint didn't work. It said that CTM (color transformation matrix) was not supported, but manjaro worked great and honestly I didn't expect it to work.

GPU: HD520 Intel 
CPU: I5 6200u
Multiple distros

**Comment by Scrumplex** [comment]
This is usually, because different distros ship with different sets of XOrg drivers by default. Using the default modeset driver seems to work the best, instead of using the xf86-video-intel driver.

**Comment by Scrumplex** [comment]
Also see #4
