### ISSUE TITLE
Cannot find output HDMI-0 in the list of supported outputs, it either does not exist or is not supported

### ISSUE THREAD

**Issue by Sempiternal-Futility** [libvibrant/libvibrant#9]
xrandr output:

> Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+  50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
DVI-0 disconnected (normal left inverted right x axis y axis)
VGA-0 disconnected (normal left inverted right x axis y axis)

when i try to run vibrant-cli

> ./vibrant-cli HDMI-0 1.5
libvibrant version 1.0.2
Cannot find output HDMI-0 in the list of supported outputs, it either does not exist or is not supported

**Comment by Scrumplex** [comment]
If you are on NVIDIA, make sure you have the proprietary driver installed.

If you are on AMD or Intel, make sure you are not using the intel or amdgpu X.Org drivers

See #4 #7
